export { default as Home } from "./Home";
export { default as Services } from "./Services";
export { default as About } from "./About";
export { default as ContactUs } from "./ContactUs";
export { default as ClientDashBoard } from "./Client/Dashboard";
export { default as ClientBookedServices } from "./Client/BookedServices";
export { default as ClientCompletedServices } from "./Client/CompletedServices";
export { default as ServiceProviderDashboard } from "./ServiceProvider/Dashboard";
export { default as ServiceProviderPostedServices } from "./ServiceProvider/PostedServices";
export { default as ServiceProviderPendingServices } from "./ServiceProvider/PendingServices";
export { default as ServiceProviderCompletedServices } from "./ServiceProvider/CompletedServices";
export { default as BrowseServices } from "./Client/BrowseServices";
export { default as BookedServices } from "./Client/BookedServices";

export { default as ClientProfile } from "./Client/Profile";
export { default as ServiceProviderProfile } from "./ServiceProvider/Profile";
export { default as AdminDashboard } from "./Admin/Dashboard";
export { default as ServiceProviderRequestedServices } from "./ServiceProvider/RequestedServices";
export { default as ClientRequestedServices } from "./Client/RequestedServices";
